apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd

data:

  context: |
    discord:
      webhook-url: $discord.webhook-url

  service.webhook.discord: |
  url: https://discord.com/api/webhooks/1505966983768838317/ti-hhffXfvbt6yCO8Is85AOgL_-AHtv1Lfx6US08FX3L5pxHwuQD4HfY6gU_B_epGmHQ
  headers:
    - name: Content-Type
      value: application/json

  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase == 'Succeeded'
      send:
        - app-sync-succeeded

  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "content": "✅ App {{.app.metadata.name}} synced"
          }