apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-eks-app
  namespace: argocd
  annotations:
    # Argo CD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: |
      backend=011528274726.dkr.ecr.eu-central-1.amazonaws.com/eks-backend:latesddt
      frontend=011528274726.dkr.ecr.eu-central-1.amazonaws.com/eks-frontend:latest
    argocd-image-updater.argoproj.io/write-back-method: git

    # Argo CD Notifications subscriptions
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.discord: "true"

spec:
  project: default

  source:
    repoURL: https://github.com/Balramch/eks-three-tier.git
    targetRevision: main
    path: k8s_charts/three-tier

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: eks-test-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
