apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-eks-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Balramch/eks-three-tier.git
    targetRevision: main
    path: k8s_charts/three-tier

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: eks-test-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
